name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - 'packages/container/**'

env:
  PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build

      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.ACCESS_KEY}}
          secret_key: ${{ secrets.SECRET_KEY }}
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
          source: packages/container/dist
          out_dir: container
          versioning: true
